Repository datsmysong/app, pull requests merged in 2024-03, with the labels that each got.

#95 feat/vote-skip
  backend/.eslintrc.json
  backend/src/RoomStorage.ts
  backend/src/musicplatform/TrackMetadata.ts
  backend/src/room.ts
  backend/src/route/AuthCallbackBindSpotifyGET.ts
  backend/src/socketio/Room.ts
  backend/src/socketio/RoomDatabase.ts
  backend/src/socketio/RoomIO.ts
  commons/backend-types.ts
  commons/socket.io-types.ts
  expo/.eslintrc.json
  expo/app/(tabs)/rooms/[id]/add.tsx
  expo/app/(tabs)/rooms/create.tsx
  expo/components/ActiveRoomView.tsx
  expo/components/CustomTextInput.tsx
  expo/components/profile/AvatarForm.tsx
  expo/components/room/TrackItem.tsx
  expo/lib/providerMethods.ts
Labels: backend, frontend

#98 feat/room-music-player
  .vscode/settings.json
  backend/src/RoomStorage.ts
  backend/src/musicplatform/Deezer.ts
  backend/src/musicplatform/MusicPlatform.ts
  backend/src/musicplatform/SoundCloud.ts
  backend/src/musicplatform/Spotify.ts
  backend/src/musicplatform/remotes/Remote.ts
  backend/src/musicplatform/remotes/SoundCloudRemote.ts
  backend/src/musicplatform/remotes/SpotifyRemote.ts
  backend/src/route/RoomPOST.ts
  backend/src/server.ts
  backend/src/socketio/Room.ts
  backend/src/socketio/RoomIO.ts
  commons/backend-types.ts
  commons/socket.io-types.ts
  expo/.eslintrc.json
  expo/app/(tabs)/rooms/[id]/_layout.tsx
  expo/app/(tabs)/rooms/[id]/index.tsx
  expo/app/components/buttons.tsx
  expo/components/ActiveRoomView.tsx
  expo/components/Button.tsx
  expo/components/Warning.tsx
  expo/components/player/LocalPlayer.tsx
  expo/components/player/Player.tsx
  expo/components/player/PlayerControls.tsx
  expo/components/player/RoomPlayer.tsx
  expo/components/player/SoundCloudPlayer.tsx
  expo/components/profile/AvatarForm.tsx
  expo/lib/audioRemote.ts
  expo/lib/soundcloud-widget-html.tsx
  expo/lib/useNetworkStatus.ts
  expo/package-lock.json
  expo/package.json
Labels: feature, backend, frontend

#140 Feat/icons
  expo/app/(tabs)/_layout.tsx
  expo/app/(tabs)/index.tsx
  expo/app/(tabs)/profile/account/index.tsx
  expo/app/(tabs)/profile/index.tsx
  expo/app/(tabs)/rooms/join.tsx
  expo/app/_layout.tsx
  expo/app/auth/connect-with-google.tsx
  expo/app/auth/connect-with-spotify.tsx
  expo/app/auth/index.tsx
  expo/app/components/warnings.tsx
  expo/components/ActiveRoomView.tsx
  expo/components/Button.tsx
  expo/components/CustomMenuOption.tsx
  expo/components/CustomPasswordInput.tsx
  expo/components/Warning.tsx
  expo/components/profile/SettingsOptions.tsx
  expo/components/room/Library.tsx
  expo/components/room/LibraryComponent.tsx
  expo/components/room/SearchedTrackItem.tsx
  expo/components/room/TrackItem.tsx
  expo/global.d.ts
  expo/lib/useTogglePasswordVisibility.ts
  expo/package-lock.json
  expo/package.json
Labels: feature, frontend

#121 feat/front-end-robustness-improvements
  .gitignore
  backend/src/RoomStorage.ts
  backend/src/musicplatform/Deezer.ts
  backend/src/musicplatform/MusicPlatform.ts
  backend/src/musicplatform/SoundCloud.ts
  backend/src/musicplatform/Spotify.ts
  backend/src/musicplatform/TrackMetadata.ts
  backend/src/musicplatform/remotes/SoundCloudRemote.ts
  backend/src/musicplatform/remotes/SpotifyRemote.ts
  backend/src/route/AuthCallbackGET.ts
  backend/src/socketio/Room.ts
  backend/src/socketio/RoomIO.ts
  commons/socket.io-types.ts
  expo/app/(tabs)/profile/account/_layout.tsx
  expo/app/(tabs)/profile/account/edit.tsx
  expo/app/(tabs)/profile/account/integration.tsx
  expo/app/(tabs)/rooms/[id]/_layout.tsx
  expo/app/components/error.tsx
  expo/components/ErrorBoundary.tsx
  expo/components/ErrorComponent/ProfileError.tsx
  expo/components/ErrorComponent/RoomError.tsx
  expo/components/ErrorComponent/RootError.tsx
  expo/components/ErrorComponent/WebsocketError.tsx
  expo/index.js
  expo/lib/AsyncError.ts
  expo/package-lock.json
  expo/package.json
  expo/tsconfig.json
Labels: feature, frontend

#144 Fix/button icons
  expo/app/(tabs)/rooms/[id]/invite.tsx
  expo/app/(tabs)/rooms/[id]/qrcode.tsx
  expo/components/RoomConfigurationParametersList.tsx
  expo/components/player/PlayerControls.tsx
  expo/components/room/TrackItem.tsx
  expo/package.json
Labels: bug
