Repository datsmysong/app, pull requests merged in 2024-04, with the labels that each got.

#66 feat/room-history-view
  backend/src/RoomStorage.ts
  backend/src/musicplatform/SoundCloud.ts
  backend/src/musicplatform/Spotify.ts
  backend/src/musicplatform/TrackMetadata.ts
  backend/src/musicplatform/remotes/SpotifyRemote.ts
  backend/src/route/RoomEndGET.ts
  backend/src/route/RoomGET.ts
  backend/src/server.ts
  backend/src/socketio/Room.ts
  commons/backend-types.ts
  commons/database-types.ts
  commons/room-types.ts
  expo/app/(tabs)/rooms/[id]/_layout.tsx
  expo/app/(tabs)/rooms/[id]/history.tsx
  expo/app/(tabs)/rooms/[id]/index.tsx
  expo/app/(tabs)/rooms/index.tsx
  expo/components/InfoCard.tsx
  expo/components/Music.tsx
  expo/components/RoomHistory.tsx
  expo/components/RoomHistoryInfoCard.tsx
  expo/components/UserRoomHistory.tsx
  expo/components/profile/Avatar.tsx
  expo/components/text/H2.tsx
  expo/lib/apiUrl.ts
  expo/lib/useRoom.tsx
  expo/lib/userProfile.ts
Labels: feature, backend, frontend

#130 ui/bottom-navigation
  expo/app/(tabs)/_layout.tsx
  expo/app/AddMusic.tsx
  expo/app/_layout.tsx
  expo/app/modal.tsx
  expo/components/Button.tsx
  expo/constants/Colors.ts
Labels: frontend

#143 feat/profile-page
  expo/app/(tabs)/profile/_layout.tsx
  expo/app/(tabs)/profile/index.tsx
  expo/components/RoomHistoryInfoCard.tsx
  expo/components/UserRoomHistory.tsx
  expo/components/profile/Avatar.tsx
  expo/components/profile/AvatarForm.tsx
  expo/components/profile/HeaderProfile.tsx
  expo/components/text/Subtitle.tsx
  expo/constants/Colors.ts
  expo/constants/Font.ts
Labels: frontend

#147 feat/temporary-friends-tab
  expo/app/(tabs)/Friends.tsx
  expo/app/(tabs)/_layout.tsx
  expo/app/(tabs)/friends.tsx
  expo/components/headers/FriendHeader.tsx
Labels: frontend

#155 docs: added final report
  Document du projet/Itération 6/S6RAIL2_DATSMYSONG_RAPPORT_FINAL.pdf
Labels: documentation

#149 feat/home-tab
  backend/src/lib/auth-utils.ts
  backend/src/musicplatform/SoundCloud.ts
  backend/src/route/RecentMusicsGET.ts
  backend/src/server.ts
  commons/database-types.ts
  expo/app/(tabs)/_layout.tsx
  expo/app/(tabs)/index.tsx
  expo/app/auth/_layout.tsx
  expo/components/ApplicationLoadingScreen.tsx
  expo/components/Music.tsx
  expo/components/UserRoomHistory.tsx
  expo/lib/userProfile.ts
Labels: frontend

#158 Feat/websocket ishost
  backend/src/socketio/RoomIO.ts
  expo/app/(tabs)/rooms/[id]/_layout.tsx
  expo/lib/socketio.ts
Labels: feature, backend, frontend

#156 feat/room-wireframe-integration
  backend/src/RoomStorage.ts
  backend/src/socketio/Room.ts
  expo/app/(tabs)/rooms/[id]/_layout.tsx
  expo/app/(tabs)/rooms/[id]/invite.tsx
  expo/app/(tabs)/rooms/index.tsx
  expo/components/ActiveRoomView.tsx
  expo/components/HeaderBack.tsx
  expo/components/player/Player.tsx
  expo/components/player/PlayerControls.tsx
  expo/components/player/RoomPlayer.tsx
  expo/components/room/MinimalistTrackItem.tsx
  expo/constants/Colors.ts
  expo/lib/room-utils.ts
Labels: frontend

#159 feat: saving music when ending room
  backend/src/route/RoomEndGET.ts
  backend/src/route/RoomGET.ts
  backend/src/socketio/Room.ts
  expo/components/RoomHistory.tsx
  expo/lib/soundcloud-widget-html.tsx
Labels: backend, frontend
