Repository datsmysong/app, pull requests merged in 2024-01, with the labels that each got.

#34 ui/button
  expo/app/(tabs)/index.tsx
  expo/app/_layout.tsx
  expo/app/components/buttons.tsx
  expo/assets/fonts/outfit/Outfit-Black.ttf
  expo/assets/fonts/outfit/Outfit-Bold.ttf
  expo/assets/fonts/outfit/Outfit-ExtraBold.ttf
  expo/assets/fonts/outfit/Outfit-ExtraLight.ttf
  expo/assets/fonts/outfit/Outfit-Light.ttf
  expo/assets/fonts/outfit/Outfit-Medium.ttf
  expo/assets/fonts/outfit/Outfit-Regular.ttf
  expo/assets/fonts/outfit/Outfit-SemiBold.ttf
  expo/assets/fonts/outfit/Outfit-Thin.ttf
  expo/components/Button.tsx
Labels: frontend

#32 feat/spotify-account
  backend/package-lock.json
  backend/package.json
  backend/src/lib/supabase.ts
  backend/src/route/AuthCallbackGET.ts
  backend/src/route/AuthRedirectionGET.ts
  backend/src/route/RoomGET.ts
  backend/src/server.ts
  backend/src/types/dbTypes.ts
  commons/Database-types.ts
  expo/.env.exemple
  expo/.gitignore
  expo/app.json
  expo/app/(auth)/_layout.tsx
  expo/app/(auth)/ask-name.tsx
  expo/app/(auth)/connect-with-spotify.tsx
  expo/app/(auth)/index.tsx
  expo/app/(auth)/login.tsx
  expo/app/(tabs)/Profile.tsx
  expo/app/_layout.tsx
  expo/components/Alert.ts
  expo/constants/Api.ts
  expo/constants/SupabaseErrorCode.ts
  expo/lib/supabase.ts
  expo/lib/useSupabaseUser.ts
  expo/lib/userProfile.ts
  expo/package-lock.json
  expo/package.json
Labels: feature

#50 fix/auth
  backend/src/route/AuthRedirectionGET.ts
  expo/app.json
  expo/app/(tabs)/Profile.tsx
  expo/app/(tabs)/_layout.tsx
  expo/app/(tabs)/rooms/_layout.tsx
  expo/app/(tabs)/rooms/index.tsx
  expo/app/_layout.tsx
  expo/app/ask-name.tsx
  expo/app/auth/_layout.tsx
  expo/app/auth/connect-with-spotify.tsx
  expo/app/auth/index.tsx
  expo/app/auth/login.tsx
  expo/lib/supabase.ts
  expo/lib/userProfile.ts
  expo/package-lock.json
  expo/package.json
Labels: bug

#51 feat/google-provider
  backend/src/route/AuthCallbackGET.ts
  expo/app.json
  expo/app/auth/connect-with-google.tsx
  expo/app/auth/connect-with-spotify.tsx
  expo/app/auth/index.tsx
  expo/lib/apiUrl.ts
  expo/lib/providerMethods.ts
Labels: feature, backend, frontend

#48 fix/create-room-backend
  backend/src/room.ts
  backend/src/route/RoomPOST.ts
  backend/src/route/StreamingServicesGET.ts
  backend/src/server.ts
  expo/app/(tabs)/rooms/create.tsx
Labels: bug

#58 docs: iteration 2 wrap up
  Document du projet/Itération 2/bilan.md
  Document du projet/Itération 2/fonctionnalitesCU.txt
Labels: documentation

#45 feat/rooms-links
  commons/database-types.ts
  expo/app/(tabs)/rooms/[id].tsx
  expo/app/(tabs)/rooms/index.tsx
  expo/app/join/[roomCode].tsx
  expo/package-lock.json
  expo/package.json
Labels: frontend

#57 feat/auth-forms
  backend/.env.local.example
  backend/package-lock.json
  backend/package.json
  backend/src/authRoutes.ts
  backend/src/route/AuthCallbackGET.ts
  backend/src/route/AuthRegisterPOST.ts
  backend/src/server.ts
  expo/app/_layout.tsx
  expo/app/auth/_layout.tsx
  expo/app/auth/index.tsx
  expo/app/auth/login.tsx
  expo/app/auth/register.tsx
  expo/components/ControlledInput.tsx
  expo/components/CustomPasswordInput.tsx
  expo/components/CustomTextInput.tsx
  expo/components/Warning.tsx
  expo/lib/authMethod.ts
  expo/lib/useTogglePasswordVisibility.ts
  expo/metro.config.js
  expo/package-lock.json
  expo/package.json
Labels: feature, frontend

#73 refactor/db-changes
  backend/src/room.ts
  backend/src/route/RoomPOST.ts
  commons/database-types-utils.ts
  commons/database-types.ts
  expo/app/(tabs)/rooms/[id].tsx
  expo/app/(tabs)/rooms/create.tsx
  expo/app/join/[roomCode].tsx
Labels: backend, frontend

#47 feat/room-queue
  .gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/RoomStorage.ts
  backend/src/musicplatform/MusicPlatform.ts
  backend/src/musicplatform/Spotify.ts
  backend/src/musicplatform/TrackFactory.ts
  backend/src/musicplatform/TrackMetadata.ts
  backend/src/room.ts
  backend/src/route/AuthCallbackGET.ts
  backend/src/route/RoomIdGET.ts
  backend/src/route/RoomPOST.ts
  backend/src/route/StreamingServicesGET.ts
  backend/src/server.ts
  backend/src/socketio/RoomIO.ts
  commons/backend-types.ts
  commons/database-types.ts
  expo/.env.exemple
  expo/app/(tabs)/_layout.tsx
  expo/app/(tabs)/rooms/[id].tsx
  expo/app/(tabs)/rooms/[id]/add.tsx
  expo/app/(tabs)/rooms/[id]/index.tsx
  expo/app/(tabs)/rooms/_layout.tsx
  expo/app/(tabs)/rooms/create.tsx
  expo/app/(tabs)/rooms/index.tsx
  expo/app/+html.tsx
  expo/components/Button.tsx
  expo/components/HView.tsx
  expo/components/room/TrackItem.tsx
  expo/lib/apiUrl.ts
  expo/lib/socketio.ts
  expo/package-lock.json
  expo/package.json
Labels: feature, backend, frontend

#79 docs/sprint-4-monday
  Document du projet/Itération 4/Journaux de bord/Gaspard.md
  Document du projet/Itération 4/Journaux de bord/Hugo.md
  Document du projet/Itération 4/Journaux de bord/Maxence.md
  Document du projet/Itération 4/Journaux de bord/Noam.md
  Document du projet/Itération 4/Journaux de bord/Thomas.md
Labels: documentation

#65 feat/join-with-code
  expo/app/(tabs)/rooms/_layout.tsx
  expo/app/(tabs)/rooms/index.tsx
  expo/app/(tabs)/rooms/join.tsx
  expo/app/join/[roomCode].tsx
  expo/lib/room-utils.ts
  expo/lib/useSupabaseUser.ts
  expo/lib/userProfile.ts
Labels: feature, frontend

#84 docs/sprint-4-tuesday-logbook
  Document du projet/Itération 4/Journaux de bord/Gaspard.md
  Document du projet/Itération 4/Journaux de bord/Hugo.md
  Document du projet/Itération 4/Journaux de bord/Maxence.md
  Document du projet/Itération 4/Journaux de bord/Noam.md
  Document du projet/Itération 4/Journaux de bord/Thomas.md
Labels: documentation

#69 feat/room-qr-code
  expo/app/(tabs)/rooms/[id]/_layout.tsx
  expo/app/(tabs)/rooms/[id]/index.tsx
  expo/app/(tabs)/rooms/[id]/invite.tsx
  expo/app/(tabs)/rooms/[id]/qrcode.tsx
  expo/app/(tabs)/rooms/_layout.tsx
  expo/app/(tabs)/rooms/index.tsx
  expo/package-lock.json
  expo/package.json
Labels: feature, frontend
